# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='density',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
