# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chembase', '0002_auto_20170728_0645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='chembase.Group'),
            preserve_default=False,
        ),
    ]
