# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chembase', '0003_auto_20170728_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chembase.Group'),
        ),
    ]
