# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembase', '0004_auto_20170728_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='pl_name',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Name (polish)'),
        ),
        migrations.AddField(
            model_name='compound',
            name='pl_subtitle',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Subtitle (polish)'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='Name (english)'),
        ),
    ]
