# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 08:35
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chembase', '0005_auto_20170802_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterModelManagers(
            name='compound',
            managers=[
                ('item_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
