# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 15:01
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chembase', '0006_auto_20170803_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['group']},
        ),
        migrations.AlterModelManagers(
            name='compound',
            managers=[
                ('existing_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
